import * as React from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import StaticDatePickerLandscape from "./calender";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Calender</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Gregorian to ,<span style={{color:"DodgerBlue"}}> Lunar </span>  calender
        </h1>
        <p className={styles.description}></p>
        <div className={styles.card}>
          <StaticDatePickerLandscape />
        </div>
      </main>
    </div>
  )
}
